### ISSUE TITLE
Where is the actual website?

### ISSUE THREAD

**Issue by Metal-Toilet** [jkunimune/dunier#1]
Apologies on how stupid this question is but where can I actually find the generator? Do I have to build it myself?

**Comment by jkunimune** [comment]
Ah, well I haven't hosted it yet because it's not finished yet.  So yes, if you want to see the WIP you would have to build it yourself.

**Comment by Metal-Toilet** [comment]
Oh okay great. This seems awesome and I can't wait until it's finished.
